# Generated by Django 3.1.3 on 2021-02-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errands', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testi', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.ImageField(upload_to='images')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='video',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='video',
            name='image_pic',
        ),
        migrations.RemoveField(
            model_name='video',
            name='vid_file',
        ),
        migrations.AddField(
            model_name='video',
            name='vid',
            field=models.FileField(null=True, upload_to='video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
